import {v4 as uuid} from "uuid"
// import product1 from "./assests/1.png"
export const Products = [
    //Pants Men
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
   
    //Shirts male
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    //Sweaters/Hoodies male
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    //Shoes male
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },








     //Pants female
     {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "pants",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },    
    //Shirts female
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "male",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shirt",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    //Sweaters/Hoodies female
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "sweaters",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    //Shoes female
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
    {
        id: uuid(),
        name: 'some name',
        description: 'some description',
        price: "$1",
        gender: "female",
        category: "shoes",
        newArrival: true,
        image: "someSrc",
        onSale: true,
    },
]